

-- Create a database of phitron company
CREATE DATABASE PHITRON;

USE PHITRON;

-- create a table of employees
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    DEPARTMENT_ID INT NOT NULL,
    SALARY INT 
);

-- create a projects table
CREATE TABLE PROJECTS(
	PROJECT_ID INT PRIMARY KEY,
    PROJECT_NAME VARCHAR(60) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    BUDGET INT
);

-- create a table named employee_projects 
CREATE TABLE EMPLOYEE_PROJECTS (
    EMPLOYEE_ID INT,
    PROJECT_ID INT,
    PRIMARY KEY (EMPLOYEE_ID, PROJECT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);


