SELECT UPPER("Shakil Ahmed");
SELECT LOWER("Shakil Ahmed");
SELECT ABS(-6);
SELECT CEIL(23.6);
SELECT FLOOR(45.5);
SELECT 10 DIV 2;



SELECT First_Name, UPPER(First_Name) 
FROM EMPLOYEES;

SELECT COS(radians(90));
SELECT ACOS(1);
SELECT PI();
SELECT RAND();

SELECT GREATEST(1,3,4,5);
SELECT LEAST(1,3,4,5);
SELECT POW(2,5);
SELECT SQRT(4);
SELECT 5 MOD 2;

