
-- JOIN/. INNER JOIN table using JOIN  
SELECT EMPLOYEES.FIRST_NAME,  DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
	INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


-- LEFT JOIN table using JOIN  
SELECT EMPLOYEES.FIRST_NAME,  DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
	LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- RIGHT JOIN table using JOIN 
SELECT EMPLOYEES.FIRST_NAME,  DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
	RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- CROSS JOIN table using JOIN   
SELECT EMPLOYEES.FIRST_NAME,  DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
	CROSS JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- JOIN, INNER JOIN, CROSS JOIN are same type

    