
-- সেই সব  department এর নাম show কর  minimum salary 5,000 থেকে বেশি

SELECT DEPARTMENT_NAME, MIN(SALARY), AVG(SALARY) 
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) > 5000;